trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Fabric-Shared-Credentials
- group: Fabric-Production

stages:
# Pre-production validation stage
- stage: PreProductionValidation
  displayName: 'Pre-Production Validation'
  jobs:
  - job: ValidateProduction
    displayName: 'Validate Production Readiness'
    steps:
    
    # Download artifacts for validation
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifacts'
      inputs:
        buildType: 'specific'
        project: '$(System.TeamProject)'
        definition: 'Fabric-CICD-Demo Build'
        buildVersionToDownload: 'latestFromBranch'
        branchName: 'refs/heads/main'
        artifactName: 'fabric-assets'
        targetPath: '$(Pipeline.Workspace)/fabric-assets'
    
    # Validate production configuration meets requirements
    - task: PowerShell@2
      displayName: 'Validate Production Configuration'
      inputs:
        targetType: 'inline'
        script: |
          $prodParamsPath = "$(Pipeline.Workspace)/fabric-assets/environments/prod/parameters.json"
          
          if (-not (Test-Path $prodParamsPath)) {
            Write-Error "Production parameters file not found"
            exit 1
          }
          
          try {
            $prodParams = Get-Content $prodParamsPath | ConvertFrom-Json -AsHashtable
            
            $validationErrors = @()
            
            if (-not $prodParams['workspaceName']) {
              $validationErrors += "Missing production workspace name"
            }
            
            if (-not $prodParams['ENVIRONMENT']) {
              $validationErrors += "Missing ENVIRONMENT setting"
            }
            
            if ($prodParams['workspaceName'] -notlike "*Production*") {
              $validationErrors += "Workspace name doesn't indicate production environment"
            }
            
            if ($prodParams['ENVIRONMENT'] -ne "prod") {
              $validationErrors += "ENVIRONMENT should be 'prod' for production deployment"
            }
            
            if ($validationErrors.Count -gt 0) {
              foreach ($error in $validationErrors) {
                Write-Host "Production validation error: $error" -ForegroundColor Red
              }
              exit 1
            }
            
            Write-Host "Production configuration validation successful"
          }
          catch {
            Write-Error "Failed to validate production config: $($_.Exception.Message)"
            exit 1
          }

# Production deployment stage
- stage: DeployProduction
  displayName: 'Deploy to Production Environment'
  dependsOn: PreProductionValidation
  condition: succeeded()
  jobs:
  - deployment: DeployProductionJob
    displayName: 'Deploy Fabric Assets to Production'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          
          # Download build artifacts
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Build Artifacts'
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProject)'
              definition: 'Fabric-CICD-Demo Build'
              buildVersionToDownload: 'latestFromBranch'
              branchName: 'refs/heads/main'
              artifactName: 'fabric-assets'
              targetPath: '$(Pipeline.Workspace)/fabric-assets'

          # Set up Python environment
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.12'
            inputs:
              versionSpec: '3.12'
              addToPath: true

          # Install required Python packages
          - script: |
              python -m pip install --upgrade pip
              pip install fabric-cicd azure-identity
            displayName: 'Install Dependencies'

          # Verify parameter.yml exists in artifacts
          - task: PowerShell@2
            displayName: 'Verify parameter.yml exists'
            inputs:
              targetType: 'inline'
              script: |
                $parameterPath = "$(Pipeline.Workspace)/fabric-assets/src/parameter.yml"
                
                if (-not (Test-Path $parameterPath)) {
                  Write-Error "parameter.yml not found at: $parameterPath"
                  exit 1
                }

          # Load production configuration variables
          - task: PowerShell@2
            displayName: 'Load Production Configuration'
            inputs:
              targetType: 'inline'
              script: |
                $prodParamsPath = "$(Pipeline.Workspace)/fabric-assets/environments/prod/parameters.json"
                $prodParams = Get-Content $prodParamsPath | ConvertFrom-Json
                
                Write-Host "##vso[task.setvariable variable=prodWorkspaceName]$($prodParams.workspaceName)"
                Write-Host "##vso[task.setvariable variable=prodEnvironment]$($prodParams.ENVIRONMENT)"

          # Authenticate to Fabric services and get workspace ID
          - task: PowerShell@2
            displayName: 'Authenticate to Fabric Services'
            inputs:
              targetType: 'inline'
              script: |
                Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser -AllowClobber
                
                try {
                  $securePassword = ConvertTo-SecureString "$(clientSecret)" -AsPlainText -Force
                  $credential = New-Object System.Management.Automation.PSCredential("$(clientId)", $securePassword)
                  
                  Connect-PowerBIServiceAccount -ServicePrincipal -Credential $credential -TenantId "$(tenantId)"
                  
                  $workspace = Get-PowerBIWorkspace -Name "$(prodWorkspaceName)"
                  if ($workspace) {
                    Write-Host "##vso[task.setvariable variable=prodWorkspaceId]$($workspace.Id)"
                    Write-Host "Production workspace found: $(prodWorkspaceName)"
                  } else {
                    Write-Error "Production workspace not found: $(prodWorkspaceName)"
                    exit 1
                  }
                }
                catch {
                  Write-Error "Authentication failed: $($_.Exception.Message)"
                  exit 1
                }

          # Deploy all assets to production with two-phase approach
          - script: |
              cd "$(Pipeline.Workspace)/fabric-assets"
              
              python -c "
              import os
              import sys
              from fabric_cicd import FabricWorkspace, publish_all_items
              from azure.identity import ClientSecretCredential

              tenant_id = os.environ['TENANT_ID']
              client_id = os.environ['CLIENT_ID']
              client_secret = os.environ['CLIENT_SECRET']
              credential = ClientSecretCredential(tenant_id=tenant_id, client_id=client_id, client_secret=client_secret)

              workspace_id = os.environ['FABRIC_WORKSPACE_ID']
              environment = os.environ['TARGET_ENVIRONMENT']

              # Deploy assets in two phases
              asset_phases = [
                  ['Lakehouse', 'Eventhouse', 'SemanticModel'],
                  ['Notebook', 'Dataflow', 'KQLDatabase', 'Report', 'KQLQueryset']
              ]
              
              for phase_num, asset_types in enumerate(asset_phases, 1):
                  print(f'Deploying Phase {phase_num}: {asset_types}')
                  try:
                      workspace = FabricWorkspace(
                          workspace_id=workspace_id,
                          repository_directory='src',
                          token_credential=credential,
                          environment=environment,
                          item_type_in_scope=asset_types
                      )
                      publish_all_items(workspace)
                      print(f'Phase {phase_num} completed successfully')
                  except Exception as e:
                      print(f'Phase {phase_num} failed: {type(e).__name__}: {e}')
                      import traceback
                      traceback.print_exc()
                      continue
              
              print('Production deployment completed')
              "
            displayName: 'Deploy All Assets to Production'
            env:
              TENANT_ID: $(tenantId)
              CLIENT_ID: $(clientId)
              CLIENT_SECRET: $(clientSecret)
              FABRIC_WORKSPACE_ID: $(prodWorkspaceId)
              TARGET_ENVIRONMENT: $(prodEnvironment)

          # Validate successful production deployment
          - task: PowerShell@2
            displayName: 'Validate Production Deployment'
            inputs:
              targetType: 'inline'
              script: |
                try {
                  Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser -AllowClobber
                  
                  $securePassword = ConvertTo-SecureString "$(clientSecret)" -AsPlainText -Force
                  $credential = New-Object System.Management.Automation.PSCredential("$(clientId)", $securePassword)
                  Connect-PowerBIServiceAccount -ServicePrincipal -Credential $credential -TenantId "$(tenantId)"
                  
                  $workspace = Get-PowerBIWorkspace -Id "$(prodWorkspaceId)"
                  if ($workspace) {
                    Write-Host "Production deployment validation successful"
                    Write-Host "Workspace: $($workspace.Name)"
                    Write-Host "Environment: $(prodEnvironment)"
                  }
                }
                catch {
                  Write-Error "Production validation failed: $($_.Exception.Message)"
                  exit 1
                }
                finally {
                  try { Disconnect-PowerBIServiceAccount } catch { }
                }

          # Generate production deployment summary
          - script: |
              echo "Production deployment completed successfully"
              echo "Environment: $(prodEnvironment)"
              echo "Workspace: $(prodWorkspaceName)"
              echo "Workspace ID: $(prodWorkspaceId)"
              echo "Configuration method: parameter.yml find_replace"
              echo "Build: $(Build.BuildNumber)"
              echo "Deployment timestamp: $(date)"
            displayName: 'Production Deployment Summary'